-- Beta seed: 10 open test jobs for customer 75eb01aa-fb92-410e-89ba-f0bb37e7efa8.
-- Run manually in the Supabase SQL Editor for the intended beta/live project.
-- This is test data only. It does not create applications, quotes, payments,
-- reviews, messages, completion proofs, workspace images, or street addresses.
--
-- Idempotency:
-- Re-running this script will not duplicate jobs with the same customer_id and
-- title. It is safe to re-run unless you manually change these seeded titles.

WITH seed_jobs (
  title,
  description,
  category,
  location,
  suburb,
  state,
  region,
  postcode,
  location_label,
  budget_min,
  budget_max,
  estimated_budget,
  budget_type,
  timeline,
  urgency,
  type
) AS (
  VALUES
    (
      'Leaking kitchen tap repair',
      'Kitchen mixer tap is leaking around the base and dripping under the sink. Looking for a licensed plumber to inspect, repair, and advise if a replacement mixer is needed.',
      'plumbing',
      'Pakenham, VIC',
      'Pakenham',
      'VIC',
      'Cardinia Shire',
      '3810',
      'Pakenham, VIC',
      180,
      180,
      180,
      'rough_estimate',
      '2026-07-01T09:00',
      'week',
      'one-off'
    ),
    (
      'Split system installation quote',
      'Need quotes for installing a supplied split system air conditioner in a single-storey home. Outdoor unit location is accessible and power location needs to be checked.',
      'electrical',
      'Officer, VIC',
      'Officer',
      'VIC',
      'Cardinia Shire',
      '3809',
      'Officer, VIC',
      750,
      750,
      750,
      'rough_estimate',
      '2026-07-03T10:30',
      'flexible',
      'one-off'
    ),
    (
      'Bathroom exhaust fan replacement',
      'Existing bathroom exhaust fan is noisy and not drawing properly. Need replacement fan supplied and installed, with the switch and ceiling cutout checked.',
      'electrical',
      'Cranbourne, VIC',
      'Cranbourne',
      'VIC',
      'City of Casey',
      '3977',
      'Cranbourne, VIC',
      260,
      260,
      260,
      'fixed_budget',
      '2026-07-05T13:00',
      'week',
      'one-off'
    ),
    (
      'Fence repair after wind damage',
      'Side paling fence has a leaning section after wind damage. Need a tradie to inspect posts, straighten where possible, and replace damaged palings.',
      'carpentry',
      'Berwick, VIC',
      'Berwick',
      'VIC',
      'City of Casey',
      '3806',
      'Berwick, VIC',
      650,
      650,
      650,
      'rough_estimate',
      '2026-07-08T08:30',
      'week',
      'one-off'
    ),
    (
      'Gutter cleaning and downpipe check',
      'Single-storey home needs gutters cleaned and downpipes checked before more winter rain. Please include disposal of leaf debris in the quote.',
      'handyman',
      'Dandenong, VIC',
      'Dandenong',
      'VIC',
      'Greater Dandenong',
      '3175',
      'Dandenong, VIC',
      300,
      300,
      300,
      'rough_estimate',
      '2026-07-02T11:00',
      'flexible',
      'one-off'
    ),
    (
      'Power point installation',
      'Need an additional double power point installed in a home office. Existing power is nearby but wall access needs to be assessed by a licensed electrician.',
      'electrical',
      'Narre Warren, VIC',
      'Narre Warren',
      'VIC',
      'City of Casey',
      '3805',
      'Narre Warren, VIC',
      280,
      280,
      280,
      'rough_estimate',
      '2026-07-04T14:15',
      'flexible',
      'one-off'
    ),
    (
      'Small deck repair',
      'Small back deck has a few loose boards and one soft section near the step. Need repair advice and replacement of damaged boards if required.',
      'carpentry',
      'Pakenham, VIC',
      'Pakenham',
      'VIC',
      'Cardinia Shire',
      '3810',
      'Pakenham, VIC',
      500,
      500,
      500,
      'rough_estimate',
      '2026-07-09T09:45',
      'flexible',
      'one-off'
    ),
    (
      'Toilet keeps running',
      'Toilet cistern keeps running after flushing and sometimes needs the button pressed again to stop. Need diagnosis and repair or replacement of internal parts.',
      'plumbing',
      'Koo Wee Rup, VIC',
      'Koo Wee Rup',
      'VIC',
      'Cardinia Shire',
      '3981',
      'Koo Wee Rup, VIC',
      220,
      220,
      220,
      'rough_estimate',
      '2026-07-06T12:00',
      'urgent',
      'one-off'
    ),
    (
      'Garage light replacement',
      'Garage fluorescent light has stopped working. Looking for a licensed electrician to replace it with an LED batten and check the switch if needed.',
      'electrical',
      'Officer, VIC',
      'Officer',
      'VIC',
      'Cardinia Shire',
      '3809',
      'Officer, VIC',
      240,
      240,
      240,
      'fixed_budget',
      '2026-07-07T15:30',
      'week',
      'one-off'
    ),
    (
      'Laundry tile repair',
      'A few laundry floor tiles are cracked near the doorway. Need quotes to remove and replace the affected tiles and re-grout the small area.',
      'tiling',
      'Cranbourne, VIC',
      'Cranbourne',
      'VIC',
      'City of Casey',
      '3977',
      'Cranbourne, VIC',
      NULL,
      NULL,
      NULL,
      'need_quotes',
      'Flexible',
      'flexible',
      'one-off'
    )
),
inserted AS (
  INSERT INTO public.jobs (
    customer_id,
    title,
    description,
    categories,
    location,
    suburb,
    state,
    region,
    postcode,
    location_label,
    budget_min,
    budget_max,
    estimated_budget,
    budget_type,
    timeline,
    urgency,
    type,
    status,
    quotes_count,
    workspace_image_count
  )
  SELECT
    '75eb01aa-fb92-410e-89ba-f0bb37e7efa8'::uuid,
    seed_jobs.title,
    seed_jobs.description,
    ARRAY[seed_jobs.category]::text[],
    seed_jobs.location,
    seed_jobs.suburb,
    seed_jobs.state,
    seed_jobs.region,
    seed_jobs.postcode,
    seed_jobs.location_label,
    seed_jobs.budget_min,
    seed_jobs.budget_max,
    seed_jobs.estimated_budget,
    seed_jobs.budget_type,
    seed_jobs.timeline,
    seed_jobs.urgency,
    seed_jobs.type,
    'open',
    0,
    0
  FROM seed_jobs
  WHERE NOT EXISTS (
    SELECT 1
    FROM public.jobs existing
    WHERE existing.customer_id = '75eb01aa-fb92-410e-89ba-f0bb37e7efa8'::uuid
      AND existing.title = seed_jobs.title
  )
  RETURNING id, title
)
SELECT count(*) AS inserted_job_count
FROM inserted;
